USE [master]
GO

/****** Object:  Database [SeliseTaskDB]    Script Date: 22/12/2023 18:37:36 ******/
CREATE DATABASE [SeliseTaskDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SeliseTaskDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SeliseTaskDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SeliseTaskDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SeliseTaskDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SeliseTaskDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SeliseTaskDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SeliseTaskDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SeliseTaskDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SeliseTaskDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SeliseTaskDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [SeliseTaskDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SeliseTaskDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SeliseTaskDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SeliseTaskDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SeliseTaskDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SeliseTaskDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SeliseTaskDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SeliseTaskDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SeliseTaskDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SeliseTaskDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SeliseTaskDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SeliseTaskDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SeliseTaskDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SeliseTaskDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SeliseTaskDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SeliseTaskDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [SeliseTaskDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SeliseTaskDB] SET RECOVERY FULL 
GO

ALTER DATABASE [SeliseTaskDB] SET  MULTI_USER 
GO

ALTER DATABASE [SeliseTaskDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SeliseTaskDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SeliseTaskDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SeliseTaskDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SeliseTaskDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SeliseTaskDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SeliseTaskDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SeliseTaskDB] SET  READ_WRITE 
GO

